import Head from 'next/head'
import Image from 'next/image'                         //this is a component of nextjs which is used as advance version of image tag in html in// using this tag you can automatically compres size of image so our website could become fast and smooth and you can also adjust size of your image more info on nextjs website // and it has also another awsome feature in which it will laod only those images which is dispalyed on our screen

import Script from 'next/script'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'     // we can import two or more css files and even if the names of the 2 or more CSS files are same then also we can use them as nextjs is so clever that it concat a special code with the css file so that there is no confuasion
import styles1 from '@/styles/Home1.module.css'
import styles2 from '@/styles/Home2.module.css'
import Link from 'next/link'
import Dummy from '@/components/Dummy'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Dummy/>
    <div className="dum">this is a taste of global</div>         {/* used a css file which is made global in dummy component*/}
       <Head>                                                                  {/*this is a function used provide head as like html  */}
        <title>Title will come here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />    {/*meta tags are used to highlight main keywords of your website so this is helpul in SEO*/}
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"></link>
        <script src='/sc.js' strategy="lazyOnload"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
      </Head>
       <Script src="/src1.js"></Script>                                           {/*this is special script component... it is used mainly for analysis services as their js coudl make my wes=bsite slow so it will be loaded after whole page is loaded you can do many things with this components for reference visit nextjs website */}
                                                                                 

<div className={'${styles1.con} ${styles2.con}'}>            {/* this is advance code which is used idk y but it has some significance*/}
<div className={styles1.con} style={{width : '18rem'}}>
  <div className="card-body">
    <h5 className="card-title">Card title</h5>
    <h6 className="card-subtitle mb-2 text-muted">Card subtitle</h6>
    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" className="card-link">Card link</a>
    <a href="#" className="card-link">Another link</a>
  </div>
</div>
<div className='dum' style={{width : '18rem'}}>          {/* used a css file which is made global in dummy component*/}
  <div className="card-body">
    <h5 className="card-title">Card title</h5>
    <h6 className="card-subtitle mb-2 text-muted">Card subtitle</h6>
    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" className="card-link">Card link</a>
    <a href="#" className="card-link">Another link</a>
  </div>
</div>
</div>   
    </>
  )
}
